{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 67}
{"name": "keyboard", "event": "release", "vk": 67}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 27}
